//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE
    {
        public int ID { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public Nullable<decimal> NUMCARTE { get; set; }
        public Nullable<int> SALAIRE { get; set; }
        public Nullable<int> CAPACITE { get; set; }
        public Nullable<int> NBABSENCE { get; set; }
        public string MATRICULE { get; set; }
        public string ENTREPRISE { get; set; }
        public string LOGINEMPLOYE { get; set; }
        public string LOGINEMPLOYEUR { get; set; }
        public Nullable<int> MOBILE { get; set; }
        public string ADRESSE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CUSER { get; set; }
        public Nullable<System.DateTime> UDATE { get; set; }
        public string UUSER { get; set; }
    }
}
